server:
  port: 8001

mybatis:
  #config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.glodon.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01              # 数据库名称
    username: root
    password: password
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间


logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.glodon: DEBUG
    com.glodon.gdmp.dao: DEBUG
eureka:
  instance:
    instance-id: microservice-dept8001 #主机名称：服务名称修改
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
info:
  app.name: glodon-microservicecloud
  company.name: www.glodon.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
