server:
  port: 80

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.glodon: DEBUG
    com.glodon.gdmp.dao: DEBUG
eureka:
  instance:
    prefer-ip-address: true
    instance-id: consumer-dept80
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: consumer-dept